#!/usr/bin/env node

// Universal instruction-spine generator (CRN-71 multi-harness).
// Reads the canonical routing table + shared rules in
// skills/cairn-trailhead/SKILL.md and writes harness/AGENTS-cairn.md — the
// cairn fragment cairn-setup appends into a project's AGENTS.md so any
// MCP-capable harness (Grok Build, Codex, Cursor, OpenCode, ...) can drive
// the same verbs the Claude Code plugin ships. Regenerate, never hand-edit;
// check-surface runs `--check` so the fragment can't drift from the registry.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "harness", "AGENTS-cairn.md");
const SENTINEL = "\u0001"; // control byte no cell can contain -- placeholder while splitting on |

const skillMd = readFileSync(join(root, "skills/cairn-trailhead/SKILL.md"), "utf8");

// --- routing table rows: | `verb` | purpose | args | subroutine | status ------
const rows = [];
for (const line of skillMd.split("\n")) {
  if (!/^\|\s*`[a-z]+`\s*\|/.test(line)) continue;
  const cells = line.replaceAll("\\|", SENTINEL).split("|")
    .map((c) => c.trim().replaceAll(SENTINEL, "\\|"));
  // cells[0] and last are empty edge artifacts of leading/trailing pipes
  const [, verb, purpose, args, , status] = cells;
  if (status === "live") {
    rows.push({ verb: verb.replaceAll("`", ""), purpose, args: args.replaceAll("`", "") });
  }
}
if (rows.length === 0) {
  console.error("gen-agents: no live verbs parsed from the routing table");
  process.exit(1);
}

// --- shared rules section, verbatim ------------------------------------------
const sharedIdx = skillMd.indexOf("## Shared rules");
if (sharedIdx < 0) {
  console.error("gen-agents: shared-rules section not found");
  process.exit(1);
}
const sharedRules = skillMd.slice(sharedIdx).trim();

const fragment = `<!-- cairn:begin — generated by scripts/gen-agents.mjs; regenerate, never hand-edit -->
# cairn — tracker-first project management

Cairn plans projects in git and mirrors every piece of work — claims,
progress comments, closes with evidence, worklogs, estimates — to the issue
tracker the team actually reads. Plans live in \`.cairn/plans/\`; the tracker
named in \`cairn.json\` is the single source of truth for work items.

**Tools:** the \`cairn\` MCP server (configure it in this harness's MCP
settings; \`cairn-setup\` does this for you). Every operation with a wrong
answer — state transitions, mirroring, drift math — is a typed tool on that
server; call tools rather than editing \`.cairn/\` state by hand.

**Running a verb:** this harness has no \`/cairn:<verb>\` slash commands —
ask for the verb by name ("run cairn status", "cairn work phase 2"). Each
verb's full subroutine lives at \`.cairn/harness/verbs/<verb>.md\` in this
project (installed by \`cairn-setup\`); read it and follow it exactly when
executing that verb.

## Verb registry

| verb | purpose | args |
|---|---|---|
${rows.map((r) => `| ${r.verb} | ${r.purpose} | ${r.args} |`).join("\n")}

${sharedRules}
<!-- cairn:end -->
`;

const checkMode = process.argv.includes("--check");
if (checkMode) {
  let existing = "";
  try {
    existing = readFileSync(OUT, "utf8");
  } catch { /* missing counts as drift */ }
  if (existing !== fragment) {
    console.error("gen-agents: harness/AGENTS-cairn.md is stale — run node scripts/gen-agents.mjs");
    process.exit(1);
  }
  process.exit(0);
}

console.log("generating AGENTS spine...");
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, fragment);
console.log(`harness/AGENTS-cairn.md written — ${rows.length} live verbs.`);
